name: bitsdojo_window
description: A package to help with creating custom windows with Flutter desktop (custom border, titlebar and minimize/maximize/close buttons) and common desktop window operations (show/hide/position on screen) for Windows and macOS
version: 0.1.1+1
homepage: https://www.bitsdojo.com
repository: https://github.com/bitsdojo/bitsdojo_window
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      windows:
        default_package: bitsdojo_window_windows
      macos:
        default_package: bitsdojo_window_macos
      linux:
        default_package: bitsdojo_window_linux

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window_platform_interface:
    git:
      url: https://github.com/xx-deps/bitsdojo_window
      path: bitsdojo_window_platform_interface
  bitsdojo_window_windows:
    git: 
      url: https://github.com/xx-deps/bitsdojo_window
      path: bitsdojo_window_windows
  bitsdojo_window_macos:
    git:
      url: https://github.com/xx-deps/bitsdojo_window
      path: bitsdojo_window_macos
  bitsdojo_window_linux:
    git:
      url: https://github.com/xx-deps/bitsdojo_window
      path: bitsdojo_window_linux
